Algoritmo "Entrada e Saída de Dados"
// 
//  
// Descrição   : Entrada e Saída de Dados
// Autor(a)    : Matheus Gremaud
// Data atual  : 10/19/2021
Var
// Seção de Declarações das variáveis 
   nome: caracter
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite seu nome:")
   leia(nome)
   escreval("Digite sua idade")
   leia(nota)
   
   escreval("Seu nome:", nome)
   escreval("Sua idade:", nota)

Fimalgoritmo