Algoritmo "variables"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matheus Gremaud
// Data atual  : 10/13/2021
Var
// Seção de Declarações das variáveis 
//primeiro nome
//segundo nome
//idade
//cidade
//endereco

      primeiroNome, segundoNome, cidade, endereco: caractere




Inicio

// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo